# Generated by Django 4.1.3 on 2024-02-18 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0036_orders_razorpay_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomtype",
            old_name="has_food_facility",
            new_name="charging_capacity",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="has_swimming_pool",
            new_name="good_mileage",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="near_airport",
            new_name="high_power",
        ),
        migrations.RenameField(
            model_name="roomtype",
            old_name="sea_area",
            new_name="high_range",
        ),
    ]
