# Generated by Django 4.1.3 on 2024-02-18 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0038_rename_room_name_roomtype_vehicle_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RoomType",
            new_name="VehicleType",
        ),
    ]
